default_stages:
  - push
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: no-commit-to-branch
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [ commit, commit-msg ]
        language: system
        entry: poetry run inv style.isort-check
        types: [ python ]
        pass_filenames: false
      - id: black
        name: black
        stages: [ commit, commit-msg ]
        language: system
        entry: poetry run inv style.black-check
        types: [ python ]
        pass_filenames: false
      - id: pylint
        name: pylint
        stages: [ commit, commit-msg ]
        language: system
        entry: poetry run inv style.pylint
        types: [ python ]
        pass_filenames: false
      - id: mypy
        name: mypy
        stages: [ commit, commit-msg ]
        language: system
        entry: poetry run inv style.mypy
        types: [ python ]
        pass_filenames: false
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.24.0
    hooks:
      - id: commitizen
        stages: [ commit-msg ]
