version: "3.3"

services:
  fast_api:
    build: ./
    restart: always
    volumes:
      - "./:/code/"
    depends_on:
      - sql_db
    environment:
      POSTGRES_SERVER: sql_db
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: 14b8991c57d7b835f880acb316485a48e8792304eff78debe66d7e16032051d9
      POSTGRES_DB: app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
    ports:
      - "8000:80"

  sql_db:
    image: postgres:15
    environment:
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: 14b8991c57d7b835f880acb316485a48e8792304eff78debe66d7e16032051d9
      POSTGRES_DB: app
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db/postgresql:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
